### PR TITLE
fix false alarm about not having debuginfo in benchmarks

### LINKED ISSUE #123: False `building without debuginfo` warning when running benchmarks
When running benchmarks there is always a false `building without debuginfo` even when they are certainly enabled and reflected in a flamegraph. This must not happen since this is very misleading.

This is most likely due to [this condition](https://github.com/flamegraph-rs/flamegraph/blob/master/src/bin/cargo-flamegraph.rs#L199-L202) that expects all binaries names to end with a target name. In practice, benchmark binaries names are in format `bench-deadbeef` like intermediate build artifacts.

### PR DESCRIPTION
**Pull request by eugene-babichenko**
Fixes #123

### CODE REVIEW

File: src/bin/cargo-flamegraph.rs [hunk 1]
```diff
@@ -210,25 +230,21 @@ fn build(opt: &Opt) {
...
-            if workload(opt)
-                .iter()
-                .any(|w| w.ends_with(&artifact.target.name))
-                && artifact.profile.debuginfo.unwrap_or(0)
-                    != 0
+            // - Check that this is a binary we are interested in.
+            //   This should start with the target name (binaries can have names in format
+            //   `benchmark-deadbeef`)
+            // - The iterator is reversed because the entities we are interested in are most likely
+            //   to appear in the of the list.
```
Comment (djc) [inline src/bin/cargo-flamegraph.rs:237]: This sentence is missing something "are most likely to appear in the [?] of the list".

File: src/bin/cargo-flamegraph.rs [hunk 2]
```diff
@@ -195,6 +195,26 @@ fn build(opt: &Opt) {
 
         let mut has_debuginfo = false;
 
+        let profile = if opt.bench.is_some() {
+            "bench"
+        } else {
+            "release"
+        };
```
Comment (djc) [inline src/bin/cargo-flamegraph.rs:202]: Moving this code seems unrelated? Would you mind putting it in a separate commit (explaining why this good)?

File: src/bin/cargo-flamegraph.rs (hunk 1 above)
Comment (eugene-babichenko) [reply src/bin/cargo-flamegraph.rs:237]: In the beginning of the list. Thanks for noting that.

**Comment by eugene-babichenko** [comment]
Fixed everything.

File: src/bin/cargo-flamegraph.rs [hunk 3]
```diff
@@ -195,6 +195,20 @@ fn build(opt: &Opt) {
...
+        let workload = workload(opt)
+            .iter()
+            .map(|w| {
+                w.parse::<PathBuf>()
+                    .unwrap()
+                    .file_name()
+                    .unwrap()
+                    .to_str()
+                    .unwrap()
+                    .to_owned()
```
Comment (djc) [inline src/bin/cargo-flamegraph.rs:214]: So I'm still a little bit stuck on this thing... Can we do something less finicky here? It's pretty confusing what's going on here, with a lot of unwrapping. Could we make this `filter_map()` and use lots of `ok()?` to just ignore the failures? I think we could do `PathBuf::from(w)` instead of `w.parse::<PathBuf>().unwrap()`?

Comment (eugene-babichenko) [reply src/bin/cargo-flamegraph.rs:214]: >  think we could do `PathBuf::from(w)`

Yes, good point.

> Could we make this `filter_map()` and use lots of `ok()?`

Yeah, makes sense, would more reliable. I am not exactly sure if this could be made simpler, we are going to use all of these operations anyway to get the file name.

**Review by djc — APPROVED** [review]
Thanks!
