### PR TITLE
Use default_run from Cargo.toml as default bin target

### LINKED ISSUE #232: Allow omitting default binary target
The readme indicates that `cargo flamegraph` is equivalent to `cargo run --release`. However, in my project with multiple binary targets it gives the following error:
```
Error: several possible targets found: [BinaryTarget { package: "astar-pairwise-aligner", target: "astar-pairwise-aligner", kind: ["bin"] }, BinaryTarget { package: "astar-pairwise-aligner", target: "proof", kind: ["bin"] }, BinaryTarget { package: "astar-pairwise-aligner", target: "generate_dataset", kind: ["bin"] }], please pass an explicit target.
```

It would be convenient to run the default binary (ie the name of the crate / the one set as `default-run` in `cargo.toml`).

Additionally it would be nice to allow the `--release` flag as a no-op, so that swapping `run` for `flamegraph` in `cargo run -r -- <flags>` _just works_.

### PR DESCRIPTION
**Pull request by RagnarGrootKoerkamp**
Fix #232 

This hides the info message when there is a single package with a `default_run` set. The code to do that came out slightly verbose though.

### CODE REVIEW

File: src/bin/cargo-flamegraph.rs [hunk 1]
```diff
@@ -310,29 +310,45 @@ fn find_unique_target(
...
 
     match targets.as_slice() {
         [_] => {
             let target = targets.remove(0);
-            eprintln!(
-                "automatically selected {} as it is the only valid target",
-                target
-            );
+            // If the selected target is the default_run of the only package, do not print a message.
+            if !(num_packages == 1 && is_default) {
```
Comment (djc) [inline src/bin/cargo-flamegraph.rs:346]: I'd prefer the `!= || !` formulation over `!(== && )`.

File: src/bin/cargo-flamegraph.rs [hunk 2]
```diff
@@ -310,29 +310,45 @@ fn find_unique_target(
...
-                    .any(|s| kind.contains(&s.as_str()))
-                    .then(|| BinaryTarget {
-                        package: name.clone(),
-                        target: t.name,
-                        kind: t.kind,
-                    })
+                let ok_kind = t.kind.iter().any(|s| kind.contains(&s.as_str()));
+                let default_filter = default_run
+                    .as_ref()
+                    .map_or(true, |default_name| &t.name == default_name);
```
Comment (djc) [inline src/bin/cargo-flamegraph.rs:332]: I'd like this rewritten as a `match` expression. Also probably good to add some comments inside the `filter_map()` closure here about what it is we're trying to achieve.

**Review by djc — COMMENTED** [review]
Thanks, some small suggestions.

**Comment by RagnarGrootKoerkamp** [comment]
done

**Review by djc — APPROVED** [review]
